# リファレンス　https://docs.docker.jp/compose/compose-file.html
# Composeリファレンスに載ってなければこっちを参照 https://docs.docker.jp/engine/reference/run.html

# Composeファイルのバージョン
version: "3"
services:
  # サービス名称　自由入力
  learndocker_mysql:
    # イメージの指定　
    image: mysql:5.7
    # マウント指定　ホスト上のパス:コンテナ上のパス
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    # 環境変数の追加
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    # 再起動ポリシー
    restart: always
  learndocker_wordpress:
    image: wordpress:php7.3-fpm
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./docker/wordpress:/var/www/html
    # サービス間依存関係の指定
    depends_on:
      - learndocker_mysql
    restart: always
  learndocker_nginx:
    image: nginx:stable
    # 公開ポート設定　ホスト側:コンテナ側　文字列推奨
    ports:
      - "${NGINX_HOST_PORT_80}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./docker/wordpress:/var/www/html
    depends_on:
      - learndocker_wordpress
    restart: always
